### ISSUE TITLE
Cant join the game

### ISSUE THREAD

**Issue by sXperfect** [ynohtna92/SlideNinjaSlide#10]
in Hero selection screen, i cant summon the hero and play the game

**Comment by ynohtna92** [comment]
I need more information. Are there any errors? Did you try disconnecting and reconnecting to the game? Are you the host of the game?

**Comment by sXperfect** [comment]
i have tried to disconnect and reconnect (even close the game and try to reconnect) but nothing works (there were 2 of 5 people experienced the same problem) I wasnt the host of the game. Is it because the dota 2 itself still have so many bugs?

**Comment by ynohtna92** [comment]
It might be possible. I'll keep this thread open to allow others to report the same issue. But it's hard to fix if i cant replicate it myself.

**Comment by ynohtna92** [comment]
Since this doesn't seem to be occurring anymore I am closing this issue.
