### ISSUE TITLE
change way of respawning ninjas.

### ISSUE THREAD

**Issue by ghost** [ynohtna92/SlideNinjaSlide#2]
currently with the respawning, it will force the camera to go way back to the spawn position. Sometimes it's noticeable, sometimes not. When it's noticeable, it's quite annoying.

I think the main reason i did it this way was because of the cool respawn particle effects/sounds. But these can just manually be added with EmitSound and CreateParticle. So we can death can be just setting the ninja underground at the same x,y, and respawn by just popping him back up ground. also apply modifier_stunned at death to prevent ability/item usage. we will also have to force camera target back to ninja.

**Comment by ynohtna92** [comment]
We could momentarily add a spawn point entity at the revival location and force the hero to spawn from there instead. It may be more elegant than pretending to kill the hero.

**Comment by ghost** [comment]
Doesn't seem to be fixed: https://www.youtube.com/watch?v=9sktv_ZyA5g&feature=youtu.be&t=8m43s

**Comment by ynohtna92** [comment]
He was playing on an older version according to http://getdotastats.com/#d2mods__match?id=899fd0118ba3ac0358d0a68485ed59fa
