### ISSUE TITLE
how to solve this problem?

### ISSUE THREAD

**Issue by dixonhau** [ynohtna92/SlideNinjaSlide#4]
after i start the custom game,it crash and show this
![capture](https://cloud.githubusercontent.com/assets/11400016/6568113/302f58b0-c70d-11e4-8106-05090c6efd8a.PNG)

**Comment by ynohtna92** [comment]
This is a workshop tools problem and unfortunately I am not able to do anything about it. Please visit dev.dota2.com and report this problem there.
