### ISSUE TITLE
The item timer will stop working when an item is picked up and destroyed.

### ISSUE THREAD

**Issue by ynohtna92** [ynohtna92/SlideNinjaSlide#6]
I don't yet understand why this is occurring but it seems to happen more when there is more than one person in the game.

**Comment by ynohtna92** [comment]
[   VScript ]: scripts/vscripts/slide_ninja_slide.lua:910: This object has been deleted from C++ and no longer exists.

**Comment by ghost** [comment]
For line 909 try:

`if self.items[self.itemindex] ~= nil and IsValidEntity(self.items[self.itemindex]) then`
