### ISSUE TITLE
The music

### ISSUE THREAD

**Issue by atomfrazze** [ynohtna92/SlideNinjaSlide#7]
The ingame music is flawless, I love it. But me and some friends have the issue that the music only plays for one person connected to the game, would love for all the players to rock out to the music at the same time.

**Comment by ghost** [comment]
I'll look into it, thanks.

**Comment by ghost** [comment]
I've fixed it, just waiting for @ynohtna92 to push the changes to the game. Thanks!

**Comment by ynohtna92** [comment]
The changes of this commit have been pushed to the game. The issue should be fixed now on the workshop @atomfrazze.

https://github.com/ynohtna92/SlideNinjaSlide/commit/78f3a84bfb3ec3f28c5832cfcf5cc5d8313713df
